spring.application.name=hibernate-demo-maven
spring.datasource.url=jdbc:postgresql://localhost:5432/PostgreDemo
spring.datasource.username=postgres
spring.datasource.password=Awsys123

logging.level.root=warn

spring.main.banner-mode=off

logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update